version: '3'
services:
  psql:
    image: postgres:${PSQL_VERSION}
    volumes:
      - ./init.sh:/init.sh:ro
      - ${DATA_PSQL}:/data
    env_file:
      - ./configs/pg.env
    entrypoint: /init.sh postgres
    environment:
      - PGDATA=/data
    shm_size: '1024g'
    ports:
      - ${DB_PORT_PSQL}:5432
