version: '3'
services:
  s64da:
    image: repo.swarm64.com/swarm64da-alveo-u200-psql-11:${S64_DA_VERSION}
    volumes:
      - ./init.sh:/init.sh:ro
      - ${DATA_S64DA}:/data
    environment:
      - PGDATA=/data
    env_file:
      - ./configs/pg.env
      - ./configs/s64da.env
    entrypoint: /init.sh postgres
    cap_add:
      - IPC_LOCK
    devices:
      - /dev/xclmgmt${XCL_MGMT_ID}:/dev/xclmgmt${XCL_MGMT_ID}
      - /dev/dri/renderD${DRI_RENDER_ID}:/dev/dri/renderD${DRI_RENDER_ID}
    shm_size: '1024g'
    ports:
      - ${DB_PORT_S64DA}:5432
