version: '3'
services:
  s64da:
    image: repo.swarm64.com/swarm64da-pac-a10-psql-11:${S64_DA_VERSION}
    volumes:
      - ./init.sh:/init.sh:ro
      - ${DATA_S64DA}:/data
      - ./license/s64da.license:/s64da.license:ro
      - /sys/class/fpga/intel-fpga-dev.0/intel-fpga-port.0:/sys/class/fpga/intel-fpga-dev.0/intel-fpga-port.0
      # - /sys/class/fpga/intel-fpga-dev.1/intel-fpga-port.1:/sys/class/fpga/intel-fpga-dev.1/intel-fpga-port.1
    environment:
      - PGDATA=/data
    env_file:
      - ./configs/pg.env
      - ./configs/s64da.env
    entrypoint: /init.sh postgres
    cap_add:
      - IPC_LOCK
    devices:
      - /dev/intel-fpga-fme.0:/dev/intel-fpga-fme.0
      - /dev/intel-fpga-port.0:/dev/intel-fpga-port.0
      # - /dev/intel-fpga-fme.1:/dev/intel-fpga-fme.1
      # - /dev/intel-fpga-port.1:/dev/intel-fpga-port.1
    shm_size: '1024g'
    ports:
      - ${DB_PORT_S64DA}:5432