version: '3'
services:
  s64da:
    image: repo.swarm64.com/swarm64da-alveo-u200-psql-11:${S64_DA_VERSION}
    volumes:
      - ./init.sh:/init.sh:ro
      - ${DATA_S64DA}:/data
      - ./license:/s64da_license      
    environment:
      - PGDATA=/data
    env_file:
      - ./configs/pg.env
      - ./configs/s64da.env
    entrypoint: /init.sh postgres
    cap_add:
      - IPC_LOCK
    devices:
      ## The Xilinx device IDs, please match to your system configuration.
      ## Device information for xclmgmt* can be collected with: ls /dev/xclmgmt*
      - /dev/xclmgmt768:/dev/xclmgmt768
      # - /dev/xclmgmt1280:/dev/xclmgmt1280
      ## Device information for renderD* can be collected with: ls /dev/dri/renderD*
      - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/dri/renderD129:/dev/dri/renderD129
    shm_size: '1024g'
    ports:
      - ${DB_PORT_S64DA}:5432
